# Generated by Django 5.2.15 on 2026-06-16 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('parent_category', models.CharField(blank=True, max_length=128, null=True)),
                ('total_products', models.IntegerField(default=0)),
                ('revenue_generated', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=128)),
                ('owner_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=64)),
                ('tax_number', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(blank=True, null=True)),
                ('segment', models.CharField(choices=[('VIP Member', 'VIP Member'), ('Standard', 'Standard'), ('New Client', 'New Client'), ('At Risk', 'At Risk')], default='Standard', max_length=64)),
                ('total_spend', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('loyalty_points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=128)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('store_id', models.CharField(max_length=64)),
                ('store_name', models.CharField(max_length=255)),
                ('joined_date', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('On Leave', 'On Leave'), ('Training', 'Training'), ('Off Duty', 'Off Duty')], default='Active', max_length=64)),
                ('avatar_url', models.URLField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesTransaction',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(default='Quick Walk-In', max_length=255)),
                ('customer_initials', models.CharField(default='WI', max_length=16)),
                ('date_time', models.CharField(max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Mobile', 'Mobile'), ('Bank', 'Bank')], default='Cash', max_length=64)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Refunded', 'Refunded'), ('Pending', 'Pending')], default='Completed', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=128, unique=True)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=64)),
                ('manager_id', models.CharField(max_length=64)),
                ('manager_name', models.CharField(max_length=255)),
                ('daily_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('sales_growth', models.FloatField(default=0.0)),
                ('inventory_count', models.IntegerField(default=0)),
                ('inventory_capacity_pct', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Maintenance', 'Maintenance')], default='Online', max_length=64)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('license_number', models.CharField(max_length=128)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('fulfillment_rate_pct', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('Preferred', 'Preferred'), ('Standard', 'Standard'), ('Overdue', 'Overdue')], default='Standard', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('low_stock', 'low_stock'), ('expiry', 'expiry'), ('purchase_order', 'purchase_order'), ('inventory_transfer', 'inventory_transfer'), ('daily_sales', 'daily_sales')], max_length=128)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('timestamp', models.CharField(max_length=128)),
                ('urgency', models.CharField(choices=[('critical', 'critical'), ('warning', 'warning'), ('info', 'info')], default='info', max_length=32)),
                ('unread', models.BooleanField(default=True)),
                ('action_required', models.BooleanField(default=False)),
                ('action_text', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=255)),
                ('item_count', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_by_name', models.CharField(max_length=255)),
                ('created_at', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('RECEIVED', 'RECEIVED')], default='PENDING', max_length=32)),
                ('delivery_status', models.CharField(blank=True, choices=[('Arrived', 'Arrived'), ('In-Transit', 'In-Transit'), ('Scheduled', 'Scheduled')], default='Scheduled', max_length=64, null=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='retail_api.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=128, unique=True)),
                ('barcode', models.CharField(db_index=True, max_length=128)),
                ('category', models.CharField(max_length=128)),
                ('brand', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=0)),
                ('reorder_level', models.IntegerField(default=10)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('Critical', 'Critical'), ('Healthy', 'Healthy'), ('Expiring', 'Expiring')], default='Healthy', max_length=32)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='retail_api.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=64)),
                ('product_name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=128)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=1)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='retail_api.salestransaction')),
            ],
        ),
    ]
